package = "ime"
version = "0.0.8"
lua = ">=5.1"

[description]
summary = "A library related to input method engine for neovim"
detailed = "rime.nvim, fcitx5-ui.nvim and ime.nvim depend on it"
maintainer = "Wu"
labels = ["neovim", "ime"]
homepage = "https://github.com/rimeinn/rime.nvim/tree/main/packages/ime"
license = 'GPL-3.0'

[source]
url = "https://github.com/rimeinn/rime.nvim/archive/$(VERSION).zip"
dir = "rime.nvim-$(VERSION)/packages/$(PACKAGE)"

[test]
type = "busted"

[build]
type = "builtin"
