package = "vim"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "use vim.fs outside of neovim"
detailed = "See :help vim.fs"
maintainer = "Wu"
labels = ["neovim"]
homepage = "https://github.com/rimeinn/rime.nvim/tree/main/packages/vim"
license = 'GPL-3.0'

[source]
url = "https://github.com/rimeinn/rime.nvim/archive/a39141f5380dda01529e4c7ca05c11d640104894.zip"
dir = "rime.nvim-a39141f5380dda01529e4c7ca05c11d640104894/packages/$(PACKAGE)"

[dependencies]
luafilesystem = " >= 1.8.0"

[test]
type = "busted"

[build]
type = "builtin"
