package = "vim"
version = "0.2.11"
lua = ">=5.1"

[description]
summary = "use vim.fs and vim.filetype outside of neovim"
detailed = "See :help vim.fs and :help vim.filetype"
maintainer = "Wu"
labels = ["neovim"]
homepage = "https://github.com/rimeinn/rime.nvim/tree/main/packages/vim"
license = 'GPL-3.0'

[source]
url = "https://github.com/rimeinn/rime.nvim/archive/$(VERSION).zip"
dir = "rime.nvim-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
luafilesystem = " >= 1.8.0"

[test]
type = "busted"

[build]
type = "builtin"
